database:
  adapter: mysql                  #sqlite3 is another option
  host: localhost                 # optional for sqlite3
  username:                       # optional for sqlite3
  password:                       # optional for sqlite3
  database:                       # optional for sqlite3
  socket: /var/mysql/mysql.sock   # optional for sqlite3
  
# sqlite3 options (defaults should not need to be changed)
database_filename: "./db/database.sqlite3"
database_export_filename: "data.sql"